name: blueautoy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  permission_handler: ^11.3.1
  get: ^4.6.6
  flutter_joystick: ^0.2.0
  flutter_xlider: ^3.5.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:  #dart run flutter_native_splash:create
  android: true
  ios: true
  web: false
  # image: "assets/images/logo2.png"
  color: "#131313"
  android_12:
    # image: "assets/images/logo2.png"
    color: "#131313"
